# Base configs
baseurl: "https://carolphotoart.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Carol Song"
subtitle: "Portrait photographer based in Bay Area"
author: "Carol Song"
header:
 title: "Photography"
 subtitle: "by Carol Song"
footer:
 name: "Hey there, my name is Carol"
 bio: "I am a photography hobbist based in San Jose, CA. I enjoy taking portrait photos. Contact me if interested in my works!"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/carol.chensong/"
